"""
Catálogo de documentos requeridos por cada tipo de trámite.

Esto define la "checklist" que se muestra en la ficha de cada cliente
(Documentos del expediente). Si un trámite no está en este diccionario
(por ejemplo "Otro"), se muestra la lista simple de documentos subidos
sin checklist.
"""

TRAMITES_DOCUMENTOS = {
    "Constitución S.L.": [
        "DNI/NIE de los socios",
        "Estatutos sociales",
        "Certificado de denominación social",
        "Justificante de capital social",
    ],
    "Declaración renta": [
        "DNI/NIE",
        "Certificado de retenciones (IRPF)",
        "Justificantes de ingresos",
        "Justificantes de gastos deducibles",
    ],
    "Autónomo alta": [
        "DNI/NIE",
        "Modelo 036/037",
        "Justificante de domicilio",
        "Certificado bancario",
    ],
    "Herencia": [
        "DNI/NIE del heredero",
        "Certificado de defunción",
        "Certificado de últimas voluntades",
        "Testamento o declaración de herederos",
        "Certificado de empadronamiento",
        "Escritura de aceptación de herencia",
    ],
    "Compraventa inmueble": [
        "DNI/NIE de las partes",
        "Nota simple registral",
        "Contrato de arras",
        "Escritura de compraventa",
        "Justificante de pago de impuestos",
    ],
    "Obtención de NIE": [
        "Pasaporte en vigor (completo, todas las páginas)",
        "Formulario EX-15 cumplimentado",
        "Justificante de pago de la tasa (modelo 790 012)",
        "Justificante del motivo de la solicitud (contrato, oferta de trabajo, compraventa, etc.)",
        "2 fotografías tamaño carnet",
    ],
    "Certificado de Registro de la UE": [
        "Pasaporte o documento de identidad en vigor",
        "Formulario EX-18 cumplimentado",
        "Justificante de pago de la tasa (modelo 790 012)",
        "Documento acreditativo de la actividad (contrato de trabajo, alta de autónomo o matrícula de estudios)",
        "Seguro médico público o privado con cobertura en España",
        "Justificante de medios económicos suficientes",
        "Certificado de empadronamiento",
    ],
    "Tarjeta de Familiar de Ciudadano de la UE": [
        "Pasaporte en vigor",
        "Formulario EX-19 cumplimentado",
        "Certificado de empadronamiento",
        "Justificante de vínculo familiar (libro de familia, certificado de matrimonio o pareja de hecho)",
        "Justificante de pago de la tasa (modelo 790 052)",
        "Certificado de registro o tarjeta del ciudadano de la UE reagrupante",
        "Seguro médico público o privado (si aplica)",
        "3 fotografías tamaño carnet",
    ],
    "Empadronamiento": [
        "DNI/NIE o pasaporte en vigor",
        "Justificante de domicilio (contrato de alquiler o escritura de propiedad)",
        "Último recibo de suministro (agua, luz o gas) a nombre del titular",
        "Autorización del titular de la vivienda y copia de su DNI (si no eres el titular)",
        "Formulario de solicitud de empadronamiento",
    ],
    "Residencia Temporal No Lucrativa": [
        "Pasaporte en vigor (mínimo 1 año de validez)",
        "Formulario de solicitud de visado nacional (EX-01)",
        "Certificado de antecedentes penales apostillado y traducido (últimos 5 años)",
        "Certificado médico",
        "Justificante de medios económicos suficientes (rentas, ahorros o inversiones)",
        "Seguro médico privado sin copago con cobertura total en España",
        "Justificante de alojamiento en España",
        "2 fotografías tamaño carnet",
    ],
    "Residencia y Trabajo por Cuenta Ajena": [
        "Pasaporte en vigor",
        "Formulario de solicitud de autorización (EX-00)",
        "Contrato de trabajo u oferta de empleo firmada por la empresa",
        "Documentación de la empresa (alta en Seguridad Social, IAE, escrituras)",
        "Certificado de antecedentes penales apostillado y traducido",
        "Certificado médico",
        "Justificante de pago de la tasa (modelo 790 052)",
        "2 fotografías tamaño carnet",
    ],
    "Residencia y Trabajo por Cuenta Propia": [
        "Pasaporte en vigor",
        "Formulario EX-07 (autorización de trabajo por cuenta propia)",
        "Memoria o proyecto de viabilidad de la actividad",
        "Cualificación profesional o experiencia acreditada (si aplica)",
        "Certificado de antecedentes penales apostillado y traducido",
        "Certificado médico",
        "Justificante de inversión o capital suficiente",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Residencia por Circunstancias Excepcionales": [
        "Pasaporte en vigor",
        "Formulario EX-10 (autorización por circunstancias excepcionales)",
        "Certificado de empadronamiento histórico (acredita permanencia continuada)",
        "Certificado de antecedentes penales (país de origen, si procede)",
        "Contrato de trabajo u oferta de empleo (arraigo laboral) o informe de inserción social (arraigo social)",
        "Justificante de vínculos familiares (arraigo familiar, si aplica)",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Residencia de Larga Duración": [
        "Pasaporte o NIE en vigor",
        "Formulario EX-11",
        "Certificado de empadronamiento",
        "Informe de vida laboral o justificante de medios económicos",
        "Certificado de antecedentes penales (si aplica)",
        "Justificante de 5 años de residencia legal continuada en España",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Reagrupación Familiar": [
        "Pasaporte en vigor del reagrupante y del familiar reagrupado",
        "Formulario EX-02 (solicitud de autorización de reagrupación familiar)",
        "Justificante de medios económicos suficientes (IPREM)",
        "Informe de adecuación de la vivienda o contrato de arrendamiento/escritura",
        "Certificado de antecedentes penales del reagrupante",
        "Justificante del vínculo familiar (libro de familia, certificado de matrimonio o de nacimiento)",
        "Certificado de empadronamiento",
        "Seguro médico del familiar reagrupado (si aplica)",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Arraigo Social": [
        "Pasaporte en vigor",
        "Formulario EX-10",
        "Certificado de empadronamiento histórico (mínimo 3 años continuados en España)",
        "Informe de arraigo/inserción social emitido por la Comunidad Autónoma",
        "Contrato de trabajo firmado por la empresa o justificante de medios económicos suficientes",
        "Certificado de antecedentes penales del país de origen (últimos 5 años)",
        "Justificante de vínculos familiares o esfuerzo de integración (si aplica)",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Arraigo Laboral": [
        "Pasaporte en vigor",
        "Formulario EX-10",
        "Certificado de empadronamiento histórico (mínimo 2 años continuados en España)",
        "Resolución judicial o acta de la Inspección de Trabajo que acredite la relación laboral (mínimo 6 meses)",
        "Certificado de antecedentes penales del país de origen",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Arraigo Familiar": [
        "Pasaporte en vigor",
        "Formulario EX-10",
        "Libro de familia o certificado de nacimiento del hijo/a español(a), o certificado de matrimonio con español(a)",
        "Certificado de nacimiento del progenitor español (si el arraigo es por ser hijo/nieto de español de origen)",
        "Certificado de empadronamiento",
        "Certificado de antecedentes penales del país de origen",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Arraigo para la Formación": [
        "Pasaporte en vigor",
        "Formulario EX-10",
        "Certificado de empadronamiento histórico (mínimo 2 años continuados en España)",
        "Matrícula en un ciclo de formación profesional o certificado de profesionalidad",
        "Compromiso de contratación de la empresa al finalizar la formación (si aplica)",
        "Certificado de antecedentes penales del país de origen",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Estancia por Estudios": [
        "Pasaporte en vigor",
        "Formulario de solicitud de autorización de estancia por estudios (EX-00)",
        "Carta de admisión del centro educativo (matrícula en curso reglado o no reglado)",
        "Justificante de medios económicos suficientes",
        "Seguro médico con cobertura total en España",
        "Certificado médico",
        "Certificado de antecedentes penales (estancias superiores a 6 meses)",
        "Justificante de alojamiento en España",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Visado de Estudios": [
        "Pasaporte en vigor (validez mínima: duración de la estancia + 3 meses)",
        "Formulario de solicitud de visado nacional",
        "Carta de admisión del centro de estudios",
        "Justificante de medios económicos suficientes",
        "Seguro médico con cobertura total",
        "Certificado médico",
        "Certificado de antecedentes penales apostillado y traducido",
        "Justificante de alojamiento en España",
        "Fotografía tamaño carnet",
        "Justificante de pago de la tasa de visado",
    ],
    "Prácticas No Laborales y Formativas": [
        "Pasaporte en vigor",
        "Formulario de solicitud de autorización de estancia por prácticas no laborales",
        "Convenio de prácticas firmado por la empresa/entidad y el centro formativo",
        "Justificante de titulación o certificado de estudios relacionado con las prácticas",
        "Justificante de medios económicos suficientes",
        "Seguro médico con cobertura total",
        "Certificado de antecedentes penales (si aplica)",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Modificación de Residencia y Trabajo": [
        "Pasaporte y NIE/TIE en vigor",
        "Formulario de solicitud de modificación (EX-00)",
        "Contrato de trabajo u oferta de empleo (o memoria de actividad si es por cuenta propia)",
        "Certificado o título académico que acredite la finalización de los estudios",
        "Certificado de empadronamiento",
        "Certificado de antecedentes penales (si procede)",
        "Justificante de pago de la tasa (modelo 790 052)",
    ],
    "Permiso de Trabajo Implícito": [
        "Pasaporte y NIE/TIE en vigor",
        "Autorización de estancia por estudios en vigor",
        "Contrato de trabajo a tiempo parcial compatible con los estudios",
        "Comunicación/alta a la Seguridad Social por parte de la empresa",
        "Justificante de compatibilidad horaria con el centro de estudios",
        "Justificante de pago de la tasa (si aplica)",
    ],
    "Nacionalidad por Residencia": [
        "Pasaporte y NIE/TIE en vigor",
        "Certificado de nacimiento apostillado y traducido",
        "Certificado de antecedentes penales del país de origen apostillado y traducido",
        "Certificado de antecedentes penales españoles",
        "Certificado de empadronamiento histórico",
        "Certificado de superación de las pruebas CCSE y DELE A2 (salvo exención)",
        "Justificante de medios de vida (vida laboral, contrato de trabajo o declaración de la renta)",
        "Formulario de solicitud (Ministerio de Justicia)",
        "Justificante de pago de la tasa (modelo 790)",
    ],
    "Nacionalidad por Carta de Naturaleza": [
        "Pasaporte en vigor",
        "Certificado de nacimiento apostillado y traducido",
        "Certificado de antecedentes penales (país de origen y España) apostillado y traducido",
        "Justificante del vínculo o motivo excepcional (p. ej. certificado sefardí de la FCJE y certificado rabínico, o informe de conexión especial con España)",
        "Certificado de superación de las pruebas CCSE y DELE (salvo exención)",
        "Formulario de solicitud",
        "Justificante de pago de la tasa",
        "Certificado de empadronamiento o justificante de residencia (si aplica)",
    ],
    "Pruebas CCSE y DELE": [
        "DNI/NIE o pasaporte en vigor",
        "Formulario de inscripción al examen (Instituto Cervantes)",
        "Justificante de pago de las tasas de examen (CCSE y DELE A2)",
        "Fotografía tamaño carnet",
        "Comprobante de cita o convocatoria de examen",
    ],
    "Ley de Memoria Democrática": [
        "Pasaporte en vigor del solicitante",
        "Certificado de nacimiento del solicitante apostillado y traducido",
        "Certificado de nacimiento del progenitor/abuelo español apostillado",
        "Certificado de matrimonio de los padres o abuelos (si aplica)",
        "Documentación acreditativa de la condición de exiliado o emigrado (certificado de salida de España, inscripción consular, documento histórico)",
        "Certificado de antecedentes penales",
        "Formulario de solicitud (sede electrónica del Ministerio de Justicia / Registro Civil)",
        "Justificante de pago de la tasa (si aplica)",
    ],
}


def documentos_requeridos(tramite):
    return TRAMITES_DOCUMENTOS.get(tramite, [])
